package br.com.rony.ecommerce.domain.entities.checkout;
public enum PaymentStatus { CREATED, PROCESSING, PENDING, REQUIRES_ACTION, APPROVED, DECLINED, CANCELLED, EXPIRED, PARTIALLY_REFUNDED, REFUNDED, CHARGEBACK, RECONCILIATION_REQUIRED }
